version: '3'
services:
  web:
    build: .
    image: myapp:latest
    volumes:
      - .:/myapp
      - myapp-bundle:/usr/local/bundle
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: password
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: mysql:5.7.42
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - myapp-mysql:/var/lib/mysql

volumes:
  myapp-mysql:
  myapp-bundle: